FROM ghcr.io/linuxserver/baseimage-ubuntu:jammy

ENV CONFIG_PATH=/config
ENV DATA_PATH=/data

ENV REG_CONFIG_PATH="${CONFIG_PATH}/registry"
ENV REG_DATA_PATH="${DATA_PATH}/registry"
ENV AUTH_CONFIG_PATH="${CONFIG_PATH}/auth"
RUN mkdir -p ${REG_CONFIG_PATH} ${REG_DATA_PATH} ${AUTH_CONFIG_PATH} && \
    chown abc:abc ${REG_CONFIG_PATH} ${REG_DATA_PATH} ${AUTH_CONFIG_PATH}

RUN apt update && \
    apt install -y cron apache2-utils

ENV REG_VERSION=2.8.2
ENV REG_ARCH=amd64
RUN curl -Ljo registry.tar.gz "https://github.com/distribution/distribution/releases/download/v${REG_VERSION}/registry_${REG_VERSION}_linux_${REG_ARCH}.tar.gz" && \
    tar -xzvf registry.tar.gz --directory /bin/ registry && \
    rm registry.tar.gz && \
    registry --version

ENV SKOPEO_CONFIG_PATH="${CONFIG_PATH}/skopeo"
ENV SKOPEO_DATA_PATH="${DATA_PATH}/skopeo"

RUN mkdir -p ${SKOPEO_CONFIG_PATH} ${SKOPEO_DATA_PATH} && \
    chown abc:abc ${SKOPEO_CONFIG_PATH} ${SKOPEO_DATA_PATH}

COPY skopeo/bin/skopeo /usr/bin/skopeo
RUN apt update && \
    apt install -y golang-github-containers-common libc6 libdevmapper1.02.1 libgpgme11 && \
    ln -s /usr/lib/x86_64-linux-gnu/libdevmapper.so.1.02.1 /usr/lib/x86_64-linux-gnu/libdevmapper.so.1.02 && \
    skopeo --version

ENV AUTH_USER=admin
ENV AUTH_PASS=changeme

ENV TZ="Asia/Shanghai"
ENV PUID=1000
ENV PGID=1000
ENV UMASK=002
COPY root/ /
COPY root-skopeo/ /
VOLUME [ "/config", "/data" ]
EXPOSE 5000
