#!/usr/bin/with-contenv bash

export HOME=${SKOPEO_DATA_PATH}

EXTRA_ARGS=""
if [ ${SKOPEO_MULTIARCH} = "true" ]; then
    EXTRA_ARGS+="--all"
fi

s6-setuidgid abc \
    skopeo sync --registries.d ${SKOPEO_DATA_PATH}/registries.d \
                --src yaml \
                --dest docker \
                --dest-creds ${AUTH_USER}:${AUTH_PASS} \
                --dest-tls-verify=false \
                --preserve-digests \
                --keep-going \
                --scoped \
                ${EXTRA_ARGS} \
            ${SKOPEO_CONFIG_PATH}/config.yml \
            localhost:5000
