#!/usr/bin/with-contenv bash

if [[ ! -f ${SKOPEO_CONFIG_PATH}/config.yml ]]; then
    echo "${SKOPEO_CONFIG_PATH}/config.yml" not exist, creat with template
    cp /etc/skopeo/config.yml.template ${SKOPEO_CONFIG_PATH}/config.yml || echo FAIL
fi

lsiown -R abc:abc ${SKOPEO_CONFIG_PATH} ${SKOPEO_DATA_PATH}

sed -i "s/SKOPEO_CONFIG_PATH=/SKOPEO_CONFIG_PATH=${SKOPEO_CONFIG_PATH}/" /etc/cron.hourly/skopeo-sync
sed -i "s/SKOPEO_DATA_PATH=/SKOPEO_DATA_PATH=${SKOPEO_DATA_PATH}/" /etc/cron.hourly/skopeo-sync
