#!/usr/bin/with-contenv bash

if [[ ! -f ${SKOPEO_CONFIG_PATH}/config.yml ]]; then
    echo "${SKOPEO_CONFIG_PATH}/config.yml" not exist, creat with template
    cp /etc/skopeo/config.yml.template ${SKOPEO_CONFIG_PATH}/config.yml || echo FAIL
fi

lsiown -R abc:abc ${SKOPEO_CONFIG_PATH} ${SKOPEO_DATA_PATH}

sed -i "s!SKOPEO_CONFIG_PATH=!SKOPEO_CONFIG_PATH=${SKOPEO_CONFIG_PATH}!" /app/skopeo-sync
sed -i "s!SKOPEO_DATA_PATH=!SKOPEO_DATA_PATH=${SKOPEO_DATA_PATH}!" /app/skopeo-sync

sed -i "s/AUTH_USER=/AUTH_USER=${AUTH_USER}/" /app/skopeo-sync
sed -i "s/AUTH_PASS=/AUTH_PASS=${AUTH_PASS}/" /app/skopeo-sync

chmod 700 /app/skopeo-sync
