#!/bin/bash -e

export HOME=${SKOPEO_DATA_PATH}
LOG=/tmp/skopeo-sync.log

s6-setuidgid abc date > ${LOG}
s6-setuidgid abc \
    skopeo sync --registries.d ${SKOPEO_DATA_PATH}/registries.d \
                --src yaml \
                --dest docker \
                --dest-creds ${AUTH_USER}:${AUTH_PASS} \
                --dest-tls-verify=false \
                --preserve-digests \
                --keep-going \
                --scoped \
            ${SKOPEO_CONFIG_PATH}/config.yml \
            localhost:5000 \
    | tee -a ${LOG}
