#!/usr/bin/with-contenv bash

if [[ ! -f ${REG_CONFIG_PATH}/config.yml ]]; then
    echo "${REG_CONFIG_PATH}/config.yml" not exist, creat with template
    cp /etc/docker/registry/config.yml.template ${REG_CONFIG_PATH}/config.yml || echo FAIL
fi

# create symbol link (not actually used now)
if [[ ! -f /etc/docker/registry/config.yml ]]; then
    ln -s ${REG_CONFIG_PATH}/config.yml /etc/docker/registry/config.yml
fi

lsiown -R abc:abc ${REG_CONFIG_PATH} ${REG_DATA_PATH}

sed -i "s!REG_CONFIG_PATH=!REG_CONFIG_PATH=${REG_CONFIG_PATH}!" /etc/cron.daily/registry-gc
sed -i "s!REG_DATA_PATH=!REG_DATA_PATH=${REG_DATA_PATH}!" /etc/cron.daily/registry-gc

chmod 700 /etc/cron.daily/registry-gc
