name: build-skopeo
on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - run: |
          git config --global user.name github-actions
          git config --global user.email github-actions@github.com
      - run: sudo apt update && sudo apt install jq curl make
      - env:
          DOCKERHUB_USER: ${{ secrets.DOCKERHUB_USER }}
          DOCKERHUB_PASS: ${{ secrets.DOCKERHUB_PASS }}
        run: |
            echo $DOCKERHUB_PASS | docker login --username $DOCKERHUB_USER --password-stdin && \
            docker buildx create --name mybuilder --bootstrap --use && \
            make build-skopeo
