name: build
on:
  push:
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        include:
          - dockerfile-suffix: ""
            tag-suffix: ""
          - dockerfile-suffix: ".skopeo"
            tag-suffix: "-skopeo"

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Get version
        id: version
        run: |
          export SKOPEO_VERSION=$(curl -s https://git.alpinelinux.org/aports/plain/community/skopeo/APKBUILD?h=3.21-stable | sed -n 's/pkgver=\([0-9.]*\)/\1/p')
          export REGISTRY_VERSION=$(sed -n -r 's/REG_VERSION \?= (.*)/\1/p' Makefile)
          echo "SKOPEO_VERSION=${SKOPEO_VERSION}" >> $GITHUB_OUTPUT
          echo "REGISTRY_VERSION=${REGISTRY_VERSION}" >> $GITHUB_OUTPUT
          if [ "${{ matrix.tag-suffix }}" = "-skopeo" ]; then
            echo "TAG_SUFFIX=-skopeo${SKOPEO_VERSION}" >> $GITHUB_OUTPUT
          else
            echo "TAG_SUFFIX=" >> $GITHUB_OUTPUT
          fi

      - name: Build
        uses: ngc7331/actions@docker-build
        with:
          name: registry
          version: ${{ steps.version.outputs.REGISTRY_VERSION }}
          suffix: ${{ matrix.tag-suffix }}
          suffix_detailed: ${{ steps.version.outputs.TAG_SUFFIX }}
          file: ./Dockerfile${{ matrix.dockerfile-suffix }}
          platforms: linux/amd64,linux/arm64
          build_args: |
            REG_VERSION=${{ steps.version.outputs.REGISTRY_VERSION }}
          DOCKERHUB_USER: ${{ secrets.DOCKERHUB_USER }}
          DOCKERHUB_PASS: ${{ secrets.DOCKERHUB_PASS }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
